name: Build ubuntu docker image 

on:
  push:
    branches:
      - feat/use-debian-image

jobs:
  release-docker:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-18.04]
        platform: [linux/arm64,linux/amd64,linux/arm/v7,linux/arm/v6]

    permissions:
      contents: write
      packages: write
      id-token: write

    steps:

      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: '0'
          ref: ${{ github.event.inputs.tag }}
          submodules: recursive

      - name: Set up ssh agent
        uses: webfactory/ssh-agent@v0.5.2
        with:
          ssh-private-key: ${{ secrets.CICD_RSA_KEY }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
        with:
          config: .github/buildkit-config.toml

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME_ROS }}
          password: ${{ secrets.DOCKER_HUB_TOKEN_ROS }}

      - name: Build and push docker images
        run: |
          make build-push-docker-images
        env:
          PLATFORM: ${{ matrix.platform }}
          SEMVER: ${{ github.event.inputs.tag }}

  combine-sign:

    needs: release-docker
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-18.04]

    permissions:
      contents: write
      packages: write
      id-token: write

    steps:

      - name: Install Cosign
        uses: sigstore/cosign-installer@main

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME_ROS }}
          password: ${{ secrets.DOCKER_HUB_TOKEN_ROS }}

      - name: Create multiarch manifest
        run: |
          docker manifest create axelarnet/axelar-core:v5.5.5 \
          axelarnet/axelar-core-linux-arm64:v5.5.5 \
          axelarnet/axelar-core-linux-amd64:v5.5.5 \
          axelarnet/axelar-core-linux-armv6:v5.5.5 \
          axelarnet/axelar-core-linux-armv7:v5.5.5
        env:
          SEMVER: ${{ github.event.inputs.tag }}

      - name: push manifest
        run: |
          docker manifest push axelarnet/axelar-core:v5.5.5
        env:
          SEMVER: v5.5.5


