name: Take testnet snapshot

on:
   push:
     branches:
       - "feat/test-backup"

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-2

      - name: Validate tag
        env:
          SEMVER: v0.29.1
        run: |
          if [[ $SEMVER =~ v[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3} ]]; then echo "Tag is okay" && exit 0; else echo "invalid tag" && exit 1; fi
          aws s3 ls s3://axelar-testnet-snapshots/axelartestnet-v0.29.1.tar.lz4 && echo "tag already exists, use a new one" && exit 1
          
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: '0'
          submodules: recursive

      - name: Copy snapshot to s3://axelar-testnet-snapshots/axelartestnet-v0.29.1.tar.lz4
        run: |
          URL=`curl -L https://quicksync.io/axelar.json|jq -r '.[] |select(.file=="axelartestnet-lisbon-3-pruned")|.url'`
          curl "$URL" | aws s3 cp - s3://axelar-testnet-snapshots/axelartestnet-v0.29.1.tar.lz4 
